spring:
# 配置存储数据的mongoDB数据库连接
  data:
    mongodb:
      username: box
      host: 127.0.0.1
      port: 27017
      password: 123456
      database: box
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spider?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root